language: node_js
node_js:
  - "0.10.25"
branches:
  only:
    - master
    - staging
    - develop
    - gh-pages
    - neo-pages
before_script:
  - gem install compass
  - gem install jekyll
  - npm install -g grunt-cli
script: "grunt --verbose"
