language: node_js
node_js:
  - "0.8"
  - "0.10"
branches:
  only:
    - master
    - staging
    - develop
    - gh-pages
before_script:
  - gem install compass
  - npm install -g grunt-cli
script: "grunt --verbose"
