# JEKYLL
exclude: ["fonts", ".gitignore", "less", "presskit", "ink.js", "Makefile", "VERSION", "LICENSE", "README.md", "icon.png", "node_modules"]

destination: ./_site

# SITE TITLE
title: Ink

# INK LATEST VERSION
latest: 2.2.0

# URLS
site_url: http://ink.sapo.pt/
download_url: 234
github_url: https://github.com/sapo/Ink

# ASSETS PATHS
images_url: img/
js_url: js/
css_url: css/
fonts_url: font/

# SITE PAGES
navigation:
 # GETTING STARTED
 - text: Getting started
   url: ./getting_started/
 # LAYOUT
 - text: Layout
   url: ./layout/
 - text: Navigation
   url: ./navigation/
 - text: Typography
   url: ./typography/
 - text: Icons
   url: ./icons/
 - text: Forms
   url: ./forms/
 - text: Alerts
   url: ./alerts/
 - text: Tables
   url: ./tables/
 - text: JavaScript Core
   url: ./javascript/core/
 - text: JavaScript UI
   submenu:
   # MODAL WINDOW
   - text: Modal
     url: ./javascript/ui/modal/
   # TABLE
   - text: Table
     url: ./javascript/ui/table/
   # TREE VIEW
   - text: Tree view
     url: ./javascript/ui/tree-view/
   # CAROUSEL
   - text: Carousel
     url: ./javascript/ui/carousel/
   # SORTABLE LIST
   - text: Sortable list
     url: ./javascript/ui/sortable-list/
   - text: Date picker
     url: ./javascript/ui/date-picker/
   - text: Tabs
     url: ./javascript/ui/tabs/
   - text: Draggables
     url: ./javascript/ui/draggables/
   - text: Droppables
     url: ./javascript/ui/droppables/
   - text: Tooltips
     url: ./javascript/ui/tooltips/
   - text: Form validator
     url: ./javascript/ui/form-validator/
 - text: Glossary
   url: ./glossary/

# ANALYTICS
# analytics: FC2C65EF-D60C-4BC2-9D76-251A50DADC3D