# JEKYLL
# exclude: ["fonts", ".gitignore", "less", "presskit", "ink.js", "Makefile", "VERSION", "LICENSE", "README.md", "icon.png"]

destination: ./_site

# SITE TITLE
title: Ink

# INK LATEST VERSION
latest: 2.2.0

# URLS
site_url: http://ink.sapo.pt/
download_url: 234
github_url: https://github.com/sapo/Ink

# ASSETS PATHS
images_url: img/
js_url: js/
css_url: css/
fonts_url: font/

# SITE PAGES
navigation:
 - text: Ink
   url: /
 - text: Getting started
   url: /getting_started/
 - text: Layout
   url: /layout/
 - text: Navigation
   url: /navigation/
 - text: Typography
   url: /typography/
 - text: Icons
   url: /icons/
 - text: Forms
   url: /forms/
 - text: Alerts
   url: /alerts/
 - text: Tables
   url: /tables/
 - text: Ink JS
   submenu: 
   - text: UI
     url: /javascript/ui/
   - text: Core
     url: /javascript/core/


# ANALYTICS
# analytics: FC2C65EF-D60C-4BC2-9D76-251A50DADC3D