# JEKYLL
exclude: [".gitignore", ".git", "config.rb", "package.json", "Gruntfile.js", ".travis.yml", "src", "less", "presskit", "Makefile", "VERSION", "LICENSE", "README.md", "icon.png", "node_modules"]

destination: ./_site

name: Ink
url: http://localhost:4000

# SITE TITLE
title: Ink

# INK LATEST VERSION
latest: 2.2.0

# URLS
site_url: http://ink.sapo.pt/
download_url: 234
github_url: https://github.com/sapo/Ink

# ASSETS PATHS
images_path: ./assets/img/
js_path: ./assets/js/
css_path: ./assets/css/
# fonts_path: assets/font/


sections:
  - title: UI Elements
    components: 
      - title: Grid
        topics:
          - title: Introduction
          - title: Dividing space
          - title: Gutters
          - title: Vertical spacing
          - title: Multiple screen sizes
          - title: Customizations
      - title: Navigation
        topics:
          - title: Introduction
          - title: Dividing space
          - title: Gutters
          - title: Vertical spacing
          - title: Multiple screen sizes
  - title: Javascript
    components: 
      - title: Dom
        topics:
          - title: Browser
          - title: Css
          - title: Element
          - title: Event
          - title: Loaded
          - title: Selector
      - title: Net
        topics:
          - title: Ajax
          - title: JsonP
      - title: UI
        topics:
          - title: Aux
          - title: Carousel
          - title: Close
          - title: DatePicker
          - title: Draggable
          - title: Droppable
          - title: FormValidator
          - title: ImageQuery
          - title: Modal
          - title: Pagination
          - title: ProgressBar
          - title: SortableList
          - title: Spy
          - title: Sticky
          - title: Table
          - title: Tabs
          - title: Toggle
          - title: Tooltip
          - title: TreeView
      - title:
        topics:
          - title: Array
          - title: BinPack
          - title: Cookie
          - title: Date
          - title: Dumper
          - title: I18n
          - title: Json
          - title: String
          - title: Swipe
          - title: Url
          - title: Validator
  - title: Cookbook
  - title: Glossary

# ANALYTICS
# analytics: FC2C65EF-D60C-4BC2-9D76-251A50DADC3D

