# JEKYLL
exclude: [".gitignore", "Gruntfile.js", ".travis.yml", "fonts", "less", "presskit", "ink.js", "Makefile", "VERSION", "LICENSE", "README.md", "icon.png", "node_modules", "_site"]

destination: ./_site

# SITE TITLE
title: Ink

# INK LATEST VERSION
latest: 2.2.0

# URLS
site_url: http://ink.sapo.pt/
download_url: 234
github_url: https://github.com/sapo/Ink

# ASSETS PATHS
images_url: img/
js_url: js/
css_url: css/
fonts_url: font/

# SITE PAGES
navigation:
 # GETTING STARTED
 - text: Getting started
   url: ./getting_started/
 # LAYOUT
 - text: Layout
   url: ./layout/
 # NAVIGATION
 - text: Navigation
   url: ./navigation/
 # TYPOGRAPHY
 - text: Typography
   url: ./typography/
 # ICONS
 - text: Icons
   url: ./icons/
 # FORMS
 - text: Forms
   url: ./forms/
 # ALERTS
 - text: Alerts
   url: ./alerts/
 # TABLES
 - text: Tables
   url: ./tables/
 # JAVASCRIPT CORE
 - text: JavaScript Core
   url: ./javascript/core/
 # JAVASCRIPT UI COMPONENTS
 - text: JavaScript UI
   submenu:
   # BEHAVIOURS
   - text: Behaviours
     url: ./javascript/ui/behaviours/
   # CAROUSEL
   - text: Carousel
     url: ./javascript/ui/carousel/
   # DATE PICKER
   - text: Date picker
     url: ./javascript/ui/date-picker/
   # DRAGGABLES
   - text: Draggables
     url: ./javascript/ui/draggables/
   # DROPPABLES
   - text: Droppables
     url: ./javascript/ui/droppables/
   # FORM VALIDATOR
   - text: Form validator
     url: ./javascript/ui/form-validator/
   # IMAGE QUERY
   - text: Image query
     url: ./javascript/ui/image-query/
   # MODAL WINDOW
   - text: Modal
     url: ./javascript/ui/modal/
   # PROGRESS BAR
   - text: Progress bar
     url: ./javascript/ui/progress-bar/
   # SORTABLE LIST
   - text: Sortable list
     url: ./javascript/ui/sortable-list/
   # TABLE
   - text: Table
     url: ./javascript/ui/table/
   # TABS
   - text: Tabs
     url: ./javascript/ui/tabs/
   # TOOLTIPS
   - text: Tooltips
     url: ./javascript/ui/tooltips/
   # TREE VIEW
   - text: Tree view
     url: ./javascript/ui/tree-view/
 # GLOSSARY
 - text: Glossary
   url: ./glossary/

# ANALYTICS
# analytics: FC2C65EF-D60C-4BC2-9D76-251A50DADC3D