# JEKYLL
exclude: [".gitignore", ".git", "config.rb", "package.json", "Gruntfile.js", ".travis.yml", "src", "less", "presskit", "Makefile", "VERSION", "LICENSE", "README.md", "icon.png", "node_modules"]

destination: ./_site

name: Ink
url: http://localhost:4000

# SITE TITLE
title: Ink

# INK LATEST VERSION
latest: 2.2.0

# URLS
site_url: http://ink.sapo.pt/
download_url: 234
github_url: https://github.com/sapo/Ink

# ASSETS PATHS
images_path: assets/img/
js_path: assets/js/
css_path: assets/css/
# fonts_path: assets/font/

# SITE PAGES
navigation:
 # GETTING STARTED
 - text: Getting started
   url: ./getting_started/
 # JAVASCRIPT CORE
 - text: JS
   url: ./js/core/
 # GLOSSARY
 - text: Glossary
   url: ./glossary/

# ANALYTICS
# analytics: FC2C65EF-D60C-4BC2-9D76-251A50DADC3D

