# SITE TITLE
title: Ink

# INK LATEST VERSION
latest: 2.2.0

# URLS
base_url: http://localhost:4000/
images_url: /assets/img/
js_url: /assets/js/
css_url: /assets/css/

# ANALYTICS
# analytics: FC2C65EF-D60C-4BC2-9D76-251A50DADC3D