title: Ink
markdown: redcarpet
pygments: true

# INK LATEST VERSION
latest: 2.2.0

# URLS
base_url: http://localhost:4000/
images_url: http://cdn.ink.sapo.pt/@LATEST/img/
js_url: http://cdn.ink.sapo.pt/@LATEST/js/
css_url: http://cdn.ink.sapo.pt/@LATEST/css/

# ANALYTICS
# analytics: FC2C65EF-D60C-4BC2-9D76-251A50DADC3D